logging:
  level:
    org.springframework: INFO
  path: /log
server:
  port: 7001
  context-path: /nontax

spring:
  redis:
    host: 192.168.65.166
    password:
    port: 6379
    timeout: 1000
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  